name: CI Pipeline - Análisis SAST con SonarQube

on:
  push:
    branches:
      - main

jobs:
  sonarQube-analysis:
    name: Análisis de Calidad de Código
    runs-on: ubuntu-latest

    steps:
      - name: Clonación del repositorio (Checkout)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Limpiar temporales
        run: |
          rm -rf ~/.sonar/cache
          mkdir -p ~/.sonar/cache

      - name: Ejecución de Escáner SonarQube
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=mi-proyecto-gestion-sw
            -Dsonar.sources=src
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.scanner.skipSslVerification=true
