name: CI Pipeline - Análisis SAST con SonarQube

on:
  push:
    branches:
      - main

jobs:
  sonarQube-analysis:
    name: Análisis de Calidad de Código
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ejecutar Scanner con Docker (Solución Anti-Hash)
        run: |
          docker run \
            --rm \
            -e SONAR_HOST_URL="${{ secrets.SONAR_HOST_URL }}" \
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=mi-proyecto-gestion-sw \
            -Dsonar.sources=. \
            -Dsonar.scanner.skipSslVerification=true \
            -Dsonar.ws.timeout=600
